# Copy this file to values.local.yaml and update it for your local cluster.
# values.local.yaml is ignored by Git.

n8n:
  publicUrl:
    host: n8n.local
    protocol: http
    port: "5678"
    webhookUrl: http://n8n.local/
    editorBaseUrl: http://n8n.local/

  proxyHops: "1"

  otel:
    enabled: true

  license:
    enabled: false

ollama:
  enabled: true
  persistence:
    size: 30Gi
  models:
    - llama3.1
