namespace: n8n

ingress:
  enabled: true
  className: nginx
  grafanaHost: grafana.local
  annotations: {}
  tls:
    enabled: true
    secretName: n8n-tls
    extraHosts: []

n8n:
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: "2.27.4"
    pullPolicy: IfNotPresent

  main:
    replicas: 2

  worker:
    replicas: 1

  publicUrl:
    host: n8n.local
    protocol: https
    port: "5678"
    webhookUrl: https://n8n.local/
    editorBaseUrl: https://n8n.local/

  proxyHops: "1"

  otel:
    enabled: true
    endpoint: http://otel-collector:4318
    tracingPath: /v1/traces
    serviceName: n8n-local
    sampleRate: "1.0"
    includeNodeSpans: "true"
    productionOnly: "false"
    injectOutbound: "true"

  license:
    enabled: false
    secretName: n8n-secrets
    secretKey: N8N_LICENSE_ACTIVATION_KEY

secrets:
  create: false
  n8nSecretName: n8n-secrets
  postgresPassword: ""
  n8nEncryptionKey: ""
  n8nLicenseActivationKey: ""

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  threshold: "1"

postgres:
  image:
    repository: postgres
    tag: "16"

redis:
  image:
    repository: redis
    tag: "7"

grafana:
  image:
    repository: grafana/grafana
    tag: "latest"
  adminUser: admin
  adminPassword: admin

prometheus:
  image:
    repository: prom/prometheus
    tag: "latest"

loki:
  image:
    repository: grafana/loki
    tag: "latest"

tempo:
  image:
    repository: grafana/tempo
    tag: "latest"

otelCollector:
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "latest"

promtail:
  image:
    repository: grafana/promtail
    tag: "latest"

ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: "latest"
  persistence:
    size: 30Gi
  models: []
