# Copy this file to values.local.yaml and update it for your local cluster.
# values.local.yaml is ignored by Git.

n8n:
  publicUrl:
    host: n8n.local
    protocol: https
    port: "5678"
    webhookUrl: https://n8n.local/
    editorBaseUrl: https://n8n.local/

  proxyHops: "1"

  otel:
    enabled: true

  license:
    enabled: false

ingress:
  enabled: true
  className: nginx
  grafanaHost: grafana.local
  tls:
    enabled: true
    secretName: n8n-tls

keda:
  enabled: true
